language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-28
    # The SDK version used to compile your project
    - android-28
    - add-on
    - extra

sudo: false
cache:
  directories:
    - node_modules

before_install:
  - nvm install 15 && nvm alias default 15 && nvm use 15
  - npm install --quiet -g npm cordova uglify-js

install:
  - cordova prepare android
# - npm install --quiet

before_script:
  - uglifyjs --compress -o js/quiz.data.js js/quiz.data.js
  
script:
  - echo "TODO"
