language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-26.0.2
    # The SDK version used to compile your project
    - android-26
    - add-on
    - extra

before_install:
  - npm install uglify-js -g

install:
  - uglifyjs --compress -o js/quiz.data.js js/quiz.data.js

script:
  - echo "TODO"